"""The bridge between the GUI widgets and the render backend.

Everything the Decoy-style UI can express lives in :class:`UIState`, and this
module is **pure Python** — no Tk, no subprocess.  That means the whole
"button -> FFmpeg flag" wiring is unit-testable headlessly, and the window
itself stays a thin renderer.

Mapping summary
---------------

========================  ======================================================
Widget                    Effect on the render
========================  ======================================================
Tier selector             picks a :class:`~reelforge.presets.Preset`
Motion blur switch        OFF -> no blur; ON -> ``tmix`` + 2x oversample
Motion blur slider        1-25 -> 2 frames, 26-50 -> 3, 51-75 -> 4, 76-100 -> 5
Output FPS selector       60 / 120 / source -> ``JobOptions.fps_override``
Sharpening switch         ON -> ``cas``, OFF -> sharpen disabled
Resolution selector       source / 1080x1920 / 720x1280 / 1080x1080 (cover crop)
Codec selector            H.264 / NVENC(GPU) / HEVC, with auto-fallback + note
========================  ======================================================
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from .models import (
    Codec,
    FitMode,
    InterpolationEngineKind,
    JobOptions,
    MotionBlurMode,
    SharpenMode,
)
from .presets import Preset, Presets
from .toolchain import Toolchain

# --------------------------------------------------------------------------- #
# widget value tables (kept here so the GUI has a single source of truth)
# --------------------------------------------------------------------------- #

#: tier id -> (label, tagline) in display order
TIER_ORDER: Tuple[str, ...] = ("turbo", "safe", "studio", "ultra120")

TIER_LABELS: Dict[str, str] = {
    "turbo": "TURBO TIER",
    "safe": "SAFE MODE TIER",
    "studio": "STUDIO TIER",
    "ultra120": "ULTRA 120FPS TIER",
}

TIER_TAGLINES: Dict[str, str] = {
    "turbo": "Sürətli 60FPS rendering",
    "safe": "TikTok Anti-Compression · GOP Bypass",
    "studio": "Maksimum keyfiyyət · High Bitrate",
    "ultra120": "AI RIFE interpolyasiya · 120FPS",
}

FPS_CHOICES: Tuple[str, ...] = ("60 FPS", "120 FPS", "SOURCE")

RESOLUTION_CHOICES: Tuple[str, ...] = (
    "SOURCE",
    "1080x1920 (9:16)",
    "720x1280 (9:16)",
    "1080x1080 (1:1)",
)

RESOLUTION_MAP: Dict[str, Tuple[Optional[int], Optional[int]]] = {
    "SOURCE": (None, None),
    "1080x1920 (9:16)": (1080, 1920),
    "720x1280 (9:16)": (720, 1280),
    "1080x1080 (1:1)": (1080, 1080),
}

CODEC_CHOICES: Tuple[str, ...] = ("H.264 (CPU)", "NVENC (GPU)", "HEVC (CPU)")

CODEC_MAP: Dict[str, Codec] = {
    "H.264 (CPU)": Codec.H264,
    "NVENC (GPU)": Codec.NVENC,
    "HEVC (CPU)": Codec.HEVC,
}


# --------------------------------------------------------------------------- #
# motion blur slider
# --------------------------------------------------------------------------- #


def blur_strength_to_params(strength: int) -> Tuple[MotionBlurMode, int, float, int]:
    """Slider position -> ``(mode, frames, amount, oversample)``.

    Motion blur is generated by oversampling to 2x the output rate and then
    averaging N frames, which is how a real 180-degree shutter behaves; the
    slider only decides how many frames get averaged.
    """
    strength = max(0, min(100, int(strength)))
    if strength == 0:
        return MotionBlurMode.OFF, 1, 0.0, 1
    if strength <= 25:
        frames = 2
    elif strength <= 50:
        frames = 3
    elif strength <= 75:
        frames = 4
    else:
        frames = 5
    return MotionBlurMode.TMIX, frames, strength / 100.0, 2


# --------------------------------------------------------------------------- #
# status text
# --------------------------------------------------------------------------- #


def status_text(phase: str = "idle", *, engine: str = "", percent: float = 0.0) -> str:
    """The phase label shown under the progress bar."""
    phase = (phase or "idle").split(":", 1)[0].strip().lower()
    if phase in {"idle", ""}:
        return "Ready — select a video"
    if phase == "probe":
        return "Analyzing…"
    if phase == "extract":
        return "Extracting frames…"
    if phase == "rife":
        if "rife" in engine.lower():
            return "Applying RIFE 120FPS…"
        return "Applying AI interpolation…"
    if phase == "encode":
        return "Encoding…"
    if phase == "dry-run":
        return "Dry run — nothing written"
    if phase == "done":
        return "Done"
    if phase == "verify":
        return "Verifying output…"
    return phase.title() + "…"


# --------------------------------------------------------------------------- #
# state
# --------------------------------------------------------------------------- #


@dataclass
class UIState:
    """Snapshot of every widget in the window."""

    tier: str = "ultra120"
    fps_choice: str = "120 FPS"
    motion_blur_enabled: bool = False
    motion_blur_strength: int = 40
    sharpen_enabled: bool = True
    sharpen_amount: float = 0.7
    resolution_choice: str = "SOURCE"
    codec_choice: str = "H.264 (CPU)"
    interpolation_choice: str = "auto"
    output_dir: Optional[Path] = None
    audio_bitrate: int = 320
    audio_sample_rate: int = 48000
    threads: int = 0
    crf_override: Optional[int] = None
    notes: List[str] = field(default_factory=list)

    # -- normalisation -------------------------------------------------------
    def preset(self) -> Preset:
        key = str(self.tier).lower().replace(" ", "").replace("_", "")
        if key.endswith("tier"):
            key = key[:-4]
        return Presets.by_id(key)

    def fps_override(self) -> Optional[int]:
        text = str(self.fps_choice).upper()
        if text.startswith("60"):
            return 60
        if text.startswith("120"):
            return 120
        return None

    def resolution(self) -> Tuple[Optional[int], Optional[int]]:
        return RESOLUTION_MAP.get(str(self.resolution_choice), (None, None))

    # -- build ---------------------------------------------------------------
    def build(self, toolchain: Optional[Toolchain] = None) -> Tuple[Preset, JobOptions]:
        """Turn the widget snapshot into ``(preset, options)``."""
        self.notes = []
        preset = self.preset()
        width, height = self.resolution()

        codec = CODEC_MAP.get(str(self.codec_choice), Codec.H264)
        codec, codec_note = resolve_codec(codec, toolchain)
        if codec_note:
            self.notes.append(codec_note)

        if self.motion_blur_enabled:
            blur_mode, blur_frames, blur_amount, oversample = blur_strength_to_params(
                self.motion_blur_strength
            )
        else:
            blur_mode, blur_frames, blur_amount, oversample = (
                MotionBlurMode.OFF, 1, 0.0, 1
            )

        sharpen = SharpenMode.CAS if self.sharpen_enabled else SharpenMode.SHARPEN_OFF

        options = JobOptions(
            output_dir=Path(self.output_dir) if self.output_dir else None,
            fit=FitMode.COVER if width and height else FitMode.KEEP,
            target_width=width,
            target_height=height,
            codec=codec,
            crf_override=self.crf_override,
            fps_override=self.fps_override(),
            interpolation_override=(
                InterpolationEngineKind(self.interpolation_choice)
                if self.interpolation_choice
                else None
            ),
            motion_blur_override=blur_mode,
            motion_blur_frames_override=blur_frames,
            motion_blur_amount_override=blur_amount,
            oversample_override=oversample,
            sharpen_override=sharpen,
            sharpen_amount_override=self.sharpen_amount if self.sharpen_enabled else 0.0,
            audio_bitrate=self.audio_bitrate,
            audio_sample_rate=self.audio_sample_rate,
            threads=self.threads,
            dual_output=False,          # the Decoy-style UI exports one file
        )
        return preset, options


def resolve_codec(
    codec: Codec, toolchain: Optional[Toolchain]
) -> Tuple[Codec, Optional[str]]:
    """Fall back to H.264 when the requested encoder is not in this build."""
    if toolchain is None:
        return codec, None
    if codec == Codec.NVENC:
        if toolchain.has_encoder("hevc_nvenc") or toolchain.has_encoder("h264_nvenc"):
            return codec, None
        return Codec.H264, (
            "NVENC tapılmadı (NVIDIA GPU/sürücü yoxdur) — H.264 (CPU) istifadə olunacaq."
        )
    if codec == Codec.HEVC and not toolchain.supports_hevc:
        return Codec.H264, "libx265 yoxdur — H.264 (CPU) istifadə olunacaq."
    return codec, None
